-- Synthetic large-schema canvas performance fixture.
-- Tables: 120. FKs: chain (entity_i -> entity_{i-1}) + hub spokes.
-- Regenerate: pnpm perf:large-schema:generate

CREATE TABLE hub_org (
  id BIGINT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE entity_001 (
  id BIGINT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_002 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_001(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_003 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_002(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_004 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_003(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_005 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_004(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_006 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_005(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_007 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_006(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_008 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_007(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_009 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_008(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_010 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_009(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_011 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_010(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_012 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_011(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_013 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_012(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_014 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_013(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_015 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_014(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_016 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_015(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_017 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_016(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_018 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_017(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_019 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_018(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_020 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_019(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_021 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_020(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_022 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_021(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_023 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_022(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_024 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_023(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_025 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_024(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_026 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_025(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_027 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_026(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_028 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_027(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_029 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_028(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_030 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_029(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_031 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_030(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_032 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_031(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_033 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_032(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_034 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_033(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_035 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_034(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_036 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_035(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_037 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_036(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_038 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_037(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_039 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_038(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_040 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_039(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_041 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_040(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_042 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_041(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_043 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_042(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_044 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_043(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_045 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_044(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_046 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_045(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_047 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_046(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_048 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_047(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_049 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_048(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_050 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_049(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_051 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_050(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_052 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_051(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_053 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_052(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_054 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_053(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_055 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_054(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_056 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_055(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_057 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_056(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_058 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_057(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_059 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_058(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_060 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_059(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_061 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_060(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_062 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_061(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_063 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_062(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_064 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_063(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_065 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_064(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_066 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_065(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_067 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_066(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_068 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_067(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_069 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_068(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_070 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_069(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_071 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_070(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_072 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_071(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_073 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_072(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_074 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_073(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_075 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_074(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_076 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_075(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_077 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_076(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_078 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_077(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_079 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_078(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_080 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_079(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_081 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_080(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_082 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_081(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_083 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_082(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_084 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_083(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_085 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_084(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_086 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_085(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_087 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_086(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_088 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_087(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_089 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_088(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_090 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_089(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_091 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_090(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_092 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_091(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_093 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_092(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_094 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_093(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_095 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_094(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_096 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_095(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_097 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_096(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_098 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_097(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_099 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_098(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_100 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_099(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_101 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_100(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_102 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_101(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_103 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_102(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_104 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_103(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_105 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_104(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_106 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_105(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_107 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_106(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_108 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_107(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_109 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_108(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_110 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_109(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_111 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_110(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_112 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_111(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_113 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_112(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_114 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_113(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_115 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_114(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_116 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_115(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_117 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_116(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_118 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_117(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_119 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_118(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE entity_120 (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES entity_119(id),
  org_id BIGINT NOT NULL REFERENCES hub_org(id),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE TABLE link_040_010 (
  id BIGINT PRIMARY KEY,
  from_id BIGINT NOT NULL REFERENCES entity_040(id),
  to_id BIGINT NOT NULL REFERENCES entity_010(id),
  note VARCHAR(255) NULL
);

CREATE TABLE link_080_020 (
  id BIGINT PRIMARY KEY,
  from_id BIGINT NOT NULL REFERENCES entity_080(id),
  to_id BIGINT NOT NULL REFERENCES entity_020(id),
  note VARCHAR(255) NULL
);

CREATE TABLE link_100_050 (
  id BIGINT PRIMARY KEY,
  from_id BIGINT NOT NULL REFERENCES entity_100(id),
  to_id BIGINT NOT NULL REFERENCES entity_050(id),
  note VARCHAR(255) NULL
);

CREATE TABLE link_120_060 (
  id BIGINT PRIMARY KEY,
  from_id BIGINT NOT NULL REFERENCES entity_120(id),
  to_id BIGINT NOT NULL REFERENCES entity_060(id),
  note VARCHAR(255) NULL
);

